// <auto-generated />
using System;
using Casa106.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Casa106.Infrastructure.Migrations
{
    [DbContext(typeof(Casa106DbContext))]
    partial class Casa106DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Casa106.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Grupo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TipoMovimiento", "Activa");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Casa106.Domain.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashArchivo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreAlmacenado")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropiedadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RespuestaIaJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaAlmacenamiento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextoExtraido")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HashArchivo")
                        .IsUnique();

                    b.HasIndex("PropiedadId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("Casa106.Domain.Entities.Movimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DocumentoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Origen")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("PeriodoDesde")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PeriodoHasta")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropiedadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Proveedor")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("PropiedadId", "Estado");

                    b.HasIndex("PropiedadId", "FechaMovimiento");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("Casa106.Domain.Entities.OcupacionMensual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IngresosAlojamiento")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NochesDisponibles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NochesOcupadas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropiedadId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TarifaPromedio")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropiedadId", "Anio", "Mes")
                        .IsUnique();

                    b.ToTable("Ocupaciones");
                });

            modelBuilder.Entity("Casa106.Domain.Entities.ProcesamientoIA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Confianza")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaProcesamiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Solicitud")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("ProcesaminetosIA");
                });

            modelBuilder.Entity("Casa106.Domain.Entities.Propiedad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidad")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Activa");

                    b.ToTable("Propiedades");
                });

            modelBuilder.Entity("Casa106.Domain.Entities.Documento", b =>
                {
                    b.HasOne("Casa106.Domain.Entities.Propiedad", "Propiedad")
                        .WithMany("Documentos")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("Casa106.Domain.Entities.Movimiento", b =>
                {
                    b.HasOne("Casa106.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Movimientos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Casa106.Domain.Entities.Documento", "Documento")
                        .WithMany("Movimientos")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Casa106.Domain.Entities.Propiedad", "Propiedad")
                        .WithMany("Movimientos")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Documento");

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("Casa106.Domain.Entities.OcupacionMensual", b =>
                {
                    b.HasOne("Casa106.Domain.Entities.Propiedad", "Propiedad")
                        .WithMany("Ocupaciones")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("Casa106.Domain.Entities.ProcesamientoIA", b =>
                {
                    b.HasOne("Casa106.Domain.Entities.Documento", "Documento")
                        .WithMany("Procesamientos")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("Casa106.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Casa106.Domain.Entities.Documento", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Procesamientos");
                });

            modelBuilder.Entity("Casa106.Domain.Entities.Propiedad", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Movimientos");

                    b.Navigation("Ocupaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
